import { EarbudModel } from './types';

export const SUPPORTED_DEVICES: EarbudModel[] = [
  {
    id: 'ear_2024_black',
    name: 'Nothing Ear (2024)',
    codename: 'entei',
    pokemonName: 'Entei',
    pokemonDexNumber: 244,
    pokemonType: ['Fire', 'Legendary'],
    pokemonFunFact: 'Nothing engineered this flagship with 45dB Smart ANC and custom 11mm ceramic drivers under the legendary codename Entei!',
    baseId: 'B171',
    sku: '69',
    leftImg: '/assets/ear_twos_black_left.webp',
    rightImg: '/assets/ear_twos_black_right.webp',
    caseImg: '/assets/ear_twos_black_case.webp',
    hasAnc: true,
    maxAncDb: 45,
    hasAdvancedEq: true,
    hasUltraBass: true,
    hasPersonalizedAnc: true,
    hasEarFitTest: true,
  },
  {
    id: 'ear_2024_white',
    name: 'Nothing Ear (2024)',
    codename: 'entei_white',
    pokemonName: 'Entei',
    pokemonDexNumber: 244,
    pokemonType: ['Fire', 'Legendary'],
    pokemonFunFact: 'Nothing flagship earbuds featuring 24-bit Hi-Res LDAC/LHDC audio and 8-band parametric EQ curves.',
    baseId: 'B171',
    sku: '70',
    leftImg: '/assets/ear_twos_white_left.webp',
    rightImg: '/assets/ear_twos_white_right.webp',
    caseImg: '/assets/ear_twos_white_case.webp',
    hasAnc: true,
    maxAncDb: 45,
    hasAdvancedEq: true,
    hasUltraBass: true,
    hasPersonalizedAnc: true,
    hasEarFitTest: true,
  },
  {
    id: 'ear_a_yellow',
    name: 'Nothing Ear (a)',
    codename: 'cleffa_yellow',
    pokemonName: 'Cleffa',
    pokemonDexNumber: 173,
    pokemonType: ['Fairy', 'Cute'],
    pokemonFunFact: 'Known internally as Cleffa, sporting the iconic bubbly bright yellow case with 45dB Active Noise Cancellation.',
    baseId: 'B162',
    sku: '65',
    leftImg: '/assets/ear_color_yellow_left.webp',
    rightImg: '/assets/ear_color_yellow_right.webp',
    caseImg: '/assets/ear_color_yellow_case.webp',
    hasAnc: true,
    maxAncDb: 45,
    hasAdvancedEq: false,
    hasUltraBass: true,
    hasPersonalizedAnc: false,
    hasEarFitTest: true,
  },
  {
    id: 'ear_a_black',
    name: 'Nothing Ear (a) Black',
    codename: 'cleffa_black',
    pokemonName: 'Cleffa',
    pokemonDexNumber: 173,
    pokemonType: ['Fairy', 'Dark'],
    pokemonFunFact: 'The sleek stealth version of Ear (a) with deep sub-bass enhancement and low-latency gaming profile.',
    baseId: 'B162',
    sku: '63',
    leftImg: '/assets/ear_color_black_left.webp',
    rightImg: '/assets/ear_color_black_right.webp',
    caseImg: '/assets/ear_color_black_case.webp',
    hasAnc: true,
    maxAncDb: 45,
    hasAdvancedEq: false,
    hasUltraBass: true,
    hasPersonalizedAnc: false,
    hasEarFitTest: true,
  },
  {
    id: 'ear_2_white',
    name: 'Nothing Ear (2)',
    codename: 'ear_2_white',
    pokemonName: 'Lugia',
    pokemonDexNumber: 249,
    pokemonType: ['Psychic', 'Flying'],
    pokemonFunFact: 'Dual chamber acoustics with custom graphene diaphragm and personalized hearing sound profile.',
    baseId: 'B155',
    sku: '17',
    leftImg: '/assets/ear_two_white_left.webp',
    rightImg: '/assets/ear_two_white_right.webp',
    caseImg: '/assets/ear_two_white_case.webp',
    duoImg: '/assets/ear_two_white_duo.webp',
    hasAnc: true,
    maxAncDb: 40,
    hasAdvancedEq: true,
    hasUltraBass: false,
    hasPersonalizedAnc: true,
    hasEarFitTest: true,
  },
  {
    id: 'ear_2_black',
    name: 'Nothing Ear (2) Black',
    codename: 'ear_2_black',
    pokemonName: 'Darkrai',
    pokemonDexNumber: 491,
    pokemonType: ['Dark', 'Mythical'],
    pokemonFunFact: 'Smoky transparent acrylic design with 40dB Personalized Active Noise Cancellation.',
    baseId: 'B155',
    sku: '27',
    leftImg: '/assets/ear_two_black_left.webp',
    rightImg: '/assets/ear_two_black_right.webp',
    caseImg: '/assets/ear_two_black_case.webp',
    duoImg: '/assets/ear_two_black_duo.webp',
    hasAnc: true,
    maxAncDb: 40,
    hasAdvancedEq: true,
    hasUltraBass: false,
    hasPersonalizedAnc: true,
    hasEarFitTest: true,
  },
  {
    id: 'ear_stick',
    name: 'Nothing Ear (stick)',
    codename: 'sticks',
    pokemonName: 'Togepi',
    pokemonDexNumber: 175,
    pokemonType: ['Fairy'],
    pokemonFunFact: 'Iconic cylindrical lipstick-twist transparent case with featherweight half-in-ear comfort.',
    baseId: 'B157',
    sku: '14',
    leftImg: '/assets/ear_stick_left.webp',
    rightImg: '/assets/ear_stick_right.webp',
    caseImg: '/assets/ear_stick_case_full.webp',
    duoImg: '/assets/ear_stick_white_duo.webp',
    hasAnc: false,
    hasAdvancedEq: true,
    hasUltraBass: true,
    hasPersonalizedAnc: false,
    hasEarFitTest: false,
  },
  {
    id: 'ear_1_white',
    name: 'Nothing Ear (1)',
    codename: 'ear_1',
    pokemonName: 'Mew',
    pokemonDexNumber: 151,
    pokemonType: ['Psychic', 'Origin'],
    pokemonFunFact: 'The legend that started it all! First generation transparent audio architecture by teenage engineering.',
    baseId: 'B181',
    sku: '01',
    leftImg: '/assets/ear_one_white_left.webp',
    rightImg: '/assets/ear_one_white_right.webp',
    caseImg: '/assets/ear_one_white_case.webp',
    duoImg: '/assets/ear_one_white_duo.webp',
    hasAnc: true,
    maxAncDb: 34,
    hasAdvancedEq: false,
    hasUltraBass: false,
    hasPersonalizedAnc: false,
    hasEarFitTest: false,
  },
  {
    id: 'cmf_buds_pro_2_blue',
    name: 'CMF Buds Pro 2',
    codename: 'espeon_blue',
    pokemonName: 'Espeon',
    pokemonDexNumber: 196,
    pokemonType: ['Psychic', 'Sun'],
    pokemonFunFact: 'Features an industry-first Smart Dial on the case to control volume, ANC, and voice assistant with tactile clicks.',
    baseId: 'B172',
    sku: '79',
    leftImg: '/assets/espeon_blue_left.webp',
    rightImg: '/assets/espeon_blue_right.webp',
    caseImg: '/assets/espeon_blue_case.webp',
    hasAnc: true,
    maxAncDb: 50,
    hasAdvancedEq: false,
    hasUltraBass: true,
    hasPersonalizedAnc: false,
    hasEarFitTest: true,
  },
  {
    id: 'cmf_buds_pro_2_orange',
    name: 'CMF Buds Pro 2 Orange',
    codename: 'espeon_orange',
    pokemonName: 'Espeon',
    pokemonDexNumber: 196,
    pokemonType: ['Psychic', 'Sun'],
    pokemonFunFact: '50dB Hybrid ANC with dual drivers (11mm bass driver + 6mm planar tweeter) for studio-grade definition.',
    baseId: 'B172',
    sku: '78',
    leftImg: '/assets/espeon_orange_left.webp',
    rightImg: '/assets/espeon_orange_right.webp',
    caseImg: '/assets/espeon_orange_case.webp',
    hasAnc: true,
    maxAncDb: 50,
    hasAdvancedEq: false,
    hasUltraBass: true,
    hasPersonalizedAnc: false,
    hasEarFitTest: true,
  },
  {
    id: 'cmf_buds_pro_orange',
    name: 'CMF Buds Pro',
    codename: 'corsola_orange',
    pokemonName: 'Corsola',
    pokemonDexNumber: 222,
    pokemonType: ['Water', 'Rock'],
    pokemonFunFact: 'Codenamed Corsola, sporting the bold energetic CMF orange colorway with 45dB Active Noise Cancellation.',
    baseId: 'B163',
    sku: '34',
    leftImg: '/assets/ear_corsola_orange_left.webp',
    rightImg: '/assets/ear_corsola_orange_right.webp',
    caseImg: '/assets/ear_corsola_orange_case.webp',
    hasAnc: true,
    maxAncDb: 45,
    hasAdvancedEq: false,
    hasUltraBass: true,
    hasPersonalizedAnc: false,
    hasEarFitTest: false,
  },
  {
    id: 'cmf_buds_orange',
    name: 'CMF Buds',
    codename: 'donphan_orange',
    pokemonName: 'Donphan',
    pokemonDexNumber: 232,
    pokemonType: ['Ground', 'Armor'],
    pokemonFunFact: 'Codenamed Donphan with a rugged aesthetic, tactile lanyard loop, and Ultra Bass Technology 2.0.',
    baseId: 'B168',
    sku: '58',
    leftImg: '/assets/donphan_orange_left.webp',
    rightImg: '/assets/donphan_orange_right.webp',
    caseImg: '/assets/donphan_orange_case.webp',
    hasAnc: true,
    maxAncDb: 42,
    hasAdvancedEq: false,
    hasUltraBass: true,
    hasPersonalizedAnc: false,
    hasEarFitTest: false,
  },
  {
    id: 'cmf_neckband_pro_orange',
    name: 'CMF Neckband Pro',
    codename: 'crobat_orange',
    pokemonName: 'Crobat',
    pokemonDexNumber: 169,
    pokemonType: ['Poison', 'Flying'],
    pokemonFunFact: 'Magnetic earbuds with intuitive 3-in-1 Smart Dial and 50dB Hybrid Active Noise Cancellation.',
    baseId: 'B164',
    sku: '48',
    leftImg: '/assets/crobat_orange.webp',
    rightImg: '/assets/crobat_orange.webp',
    caseImg: '/assets/crobat_orange.webp',
    duoImg: '/assets/crobat_orange.webp',
    hasAnc: true,
    maxAncDb: 50,
    hasAdvancedEq: false,
    hasUltraBass: true,
    hasPersonalizedAnc: false,
    hasEarFitTest: false,
    hasCaseLedColor: true,
  },
  {
    id: 'ear_open_white',
    name: 'Nothing Ear (open)',
    codename: 'flaaffy',
    pokemonName: 'Flaaffy',
    pokemonDexNumber: 180,
    pokemonType: ['Electric'],
    pokemonFunFact: 'Nothing innovative open-ear acoustic system with directional sound projection and stepped driver design.',
    baseId: 'B174',
    sku: '11200005',
    leftImg: '/assets/flaffy_white_left.webp',
    rightImg: '/assets/flaffy_white_right.webp',
    caseImg: '/assets/flaffy_white_case.webp',
    hasAnc: false,
    hasAdvancedEq: true,
    hasUltraBass: true,
    hasPersonalizedAnc: false,
    hasEarFitTest: false,
  },
];

export const SKU_TO_MODEL_MAP: Record<string, string> = {
  '01': 'ear_1_white',
  '02': 'ear_1_white',
  '14': 'ear_stick',
  '15': 'ear_stick',
  '17': 'ear_2_white',
  '27': 'ear_2_black',
  '34': 'cmf_buds_pro_orange',
  '30': 'cmf_buds_pro_orange',
  '69': 'ear_2024_black',
  '70': 'ear_2024_white',
  '65': 'ear_a_yellow',
  '63': 'ear_a_black',
  '64': 'ear_a_yellow',
  '78': 'cmf_buds_pro_2_orange',
  '79': 'cmf_buds_pro_2_blue',
  '76': 'cmf_buds_pro_2_blue',
  '80': 'cmf_buds_pro_2_blue',
  '81': 'cmf_buds_pro_2_orange',
  '82': 'cmf_buds_pro_2_blue',
  '83': 'cmf_buds_pro_2_blue',
  '97': 'cmf_buds_pro_2_blue',
  '51': 'cmf_buds_pro_2_blue',
  '58': 'cmf_buds_orange',
  '54': 'cmf_buds_orange',
  '48': 'cmf_neckband_pro_orange',
  '11200005': 'ear_open_white',
};

export function findModelBySku(sku: string, serial: string = ''): EarbudModel {
  if (serial.startsWith('13')) {
    // 13 is CMF product line
    const modelId = SKU_TO_MODEL_MAP[sku] || 'cmf_buds_pro_2_blue';
    return SUPPORTED_DEVICES.find(d => d.id === modelId) || SUPPORTED_DEVICES.find(d => d.id === 'cmf_buds_pro_2_blue')!;
  }
  const modelId = SKU_TO_MODEL_MAP[sku] || 'ear_2024_black';
  return SUPPORTED_DEVICES.find(d => d.id === modelId) || SUPPORTED_DEVICES[0];
}

export function findModelByBase(baseId: string): EarbudModel {
  return SUPPORTED_DEVICES.find(d => d.baseId === baseId) || SUPPORTED_DEVICES[0];
}

export function findModelByName(name: string): EarbudModel {
  const n = name.toLowerCase();
  if (n.includes('pro 2') || n.includes('buds 2') || n.includes('espeon')) {
    return SUPPORTED_DEVICES.find(d => d.id === 'cmf_buds_pro_2_blue') || SUPPORTED_DEVICES[0];
  }
  if (n.includes('neckband') || n.includes('crobat')) {
    return SUPPORTED_DEVICES.find(d => d.id === 'cmf_neckband_pro_orange') || SUPPORTED_DEVICES[0];
  }
  if (n.includes('buds pro') || n.includes('corsola')) {
    return SUPPORTED_DEVICES.find(d => d.id === 'cmf_buds_pro_orange') || SUPPORTED_DEVICES[0];
  }
  if (n.includes('cmf') || n.includes('donphan')) {
    return SUPPORTED_DEVICES.find(d => d.id === 'cmf_buds_orange') || SUPPORTED_DEVICES[0];
  }
  if (n.includes('ear (stick)') || n.includes('stick')) {
    return SUPPORTED_DEVICES.find(d => d.id === 'ear_stick') || SUPPORTED_DEVICES[0];
  }
  if (n.includes('ear (2)') || n.includes('ear 2')) {
    return SUPPORTED_DEVICES.find(d => d.id === 'ear_2_black') || SUPPORTED_DEVICES[0];
  }
  if (n.includes('ear (a)') || n.includes('ear a') || n.includes('cleffa')) {
    return SUPPORTED_DEVICES.find(d => d.id === 'ear_a_yellow') || SUPPORTED_DEVICES[0];
  }
  if (n.includes('ear (1)') || n.includes('ear 1')) {
    return SUPPORTED_DEVICES.find(d => d.id === 'ear_1_white') || SUPPORTED_DEVICES[0];
  }
  if (n.includes('ear (open)') || n.includes('open') || n.includes('flaaffy')) {
    return SUPPORTED_DEVICES.find(d => d.id === 'ear_open_white') || SUPPORTED_DEVICES[0];
  }
  return SUPPORTED_DEVICES.find(d => d.id === 'ear_2024_black') || SUPPORTED_DEVICES[0];
}


